---
title: "fit ebpmf to sla data with non-negative constraints, new version with different baseline"
author: "DongyueXie"
date: "2023-07-22"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r}
library(Matrix)
datax = readRDS('data/sla_2000.rds')
dim(datax$data)
sum(datax$data==0)/prod(dim(datax$data))
datax$data = Matrix(datax$data,sparse = TRUE)
```

## Topic model fit

Give the structure plot

```{r,eval=F}
library(fastTopics)
fit_tm = fit_topic_model(datax$data,k=6)

```

perform de analysis to find driving genes for each cluster
```{r,eval=F}
temp = de_analysis(fit_tm,datax$data)

saveRDS(list(fit_tm=fit_tm,de=temp),file='/project2/mstephens/dongyue/poisson_mf/sla/sla2000_tm_fit.rds')
```

```{r}
library(fastTopics)
res = readRDS("/project2/mstephens/dongyue/poisson_mf/sla/sla2000_tm_fit.rds")
structure_plot(res$fit_tm,grouping = datax$samples$journal,gap = 40)
structure_plot(res$fit_tm,grouping = datax$samples$year,gap = 40)

for(k in 1:6){
  dat <- data.frame(postmean = res$de$postmean[,k],
                  z        = res$de$z[,k],
                  lfsr     = res$de$lfsr[,k])
rownames(dat) <- colnames(datax$data)
dat <- subset(dat,lfsr < 0.01)
dat <- dat[order(dat$postmean,decreasing = TRUE),]
print(head(dat,n=10))
print(tail(dat,n=10))

  #print(colnames(datax$data)[order(temp$lfsr[,k],decreasing = F)[1:10]])
}

```


## EBNMF fit

```{r}
library(flashier)
library(ebpmf)

Y_tilde = log_for_ebmf(datax$data)
fit_flash = flash(Y_tilde,ebnm_fn = ebnm::ebnm_point_exponential,var_type = 2,backfit = T,greedy_Kmax = 10)
for(k in 1:fit_flash$n_factors){
  print(colnames(datax$data)[order(fit_flash$F_pm[,k],decreasing = T)[1:10]])
}

```

```{r}
# input: fit, topics, grouping

# poisson2multinom
#
library(fastTopics)
library(ggplot2)
library(gridExtra)
structure_plot_general = function(Lhat,Fhat,grouping,title=NULL,
                                  loadings_order = 'embed',
                                  print_plot=TRUE,
                                  seed=12345,
                                  n_samples = NULL,
                                  gap=40,
                                  std_L_method = 'sum_to_1',
                                  show_legend=TRUE,
                                  K = NULL,
                                  colors = c('#a6cee3',
                                    '#1f78b4',
                                    '#b2df8a',
                                    '#33a02c',
                                    '#fb9a99',
                                    '#e31a1c',
                                    '#fdbf6f',
                                    '#ff7f00',
                                    '#cab2d6',
                                    '#6a3d9a',
                                    '#ffff99',
                                    '#b15928')){
  set.seed(seed)
  #s       <- apply(Lhat,2,max)
  #Lhat    <-	t(t(Lhat) / s)

  if(is.null(n_samples)&all(loadings_order == "embed")){
    n_samples = 2000
  }

  if(std_L_method=='sum_to_1'){
    Lhat = Lhat/rowSums(Lhat)
  }
  if(std_L_method=='row_max_1'){
    Lhat = Lhat/c(apply(Lhat,1,max))
  }
  if(std_L_method=='col_max_1'){
    Lhat = apply(Lhat,2,function(z){z/max(z)})
  }
  if(std_L_method=='col_norm_1'){
    Lhat = apply(Lhat,2,function(z){z/norm(z,'2')})
  }
  
  if(!is.null(K)){
    Lhat = Lhat[,1:K]
    Fhat = Fhat[,1:K]
  }
  Fhat = matrix(1,nrow=3,ncol=ncol(Lhat))
  if(is.null(colnames(Lhat))){
    colnames(Lhat) <- paste0("k",1:ncol(Lhat))
  }
  fit_list     <- list(L = Lhat,F = Fhat)
  class(fit_list) <- c("multinom_topic_model_fit", "list")
  p <- structure_plot(fit_list,grouping = grouping,
                      loadings_order = loadings_order,
                      n = n_samples,gap = gap,colors=colors,verbose=F) +
    labs(y = "loading",color = "dim",fill = "dim") + ggtitle(title)
  if(!show_legend){
    p <- p + theme(legend.position="none")
  }
  if(print_plot){
    print(p)
  }
  return(p)
}
```

```{r}
p1=structure_plot_general(fit_flash$L_pm,fit_flash$F_pm,grouping = datax$samples$journal,std_L_method = 'sum_to_1')
p2=structure_plot_general(fit_flash$L_pm,fit_flash$F_pm,grouping = datax$samples$journal,std_L_method = 'row_max_1')
p3=structure_plot_general(fit_flash$L_pm,fit_flash$F_pm,grouping = datax$samples$journal,std_L_method = 'col_norm_1')
p4=structure_plot_general(fit_flash$L_pm,fit_flash$F_pm,grouping = datax$samples$journal,std_L_method = 'col_max_1')
```

## EBPMF fit 

### Init 1

```{r}
library(ebpmf)
# fit_ebpmf1 = ebpmf_log(datax$data,
#                       flash_control=list(backfit_extrapolate=T,backfit_warmstart=T,
#                                          ebnm.fn = c(ebnm::ebnm_point_exponential, ebnm::ebnm_point_exponential),
#                                          loadings_sign = 1,factors_sign=1,Kmax=10),
#                       init_control = list(n_cores=5,flash_est_sigma2=F,log_init_for_non0y=T),
#                       general_control = list(maxiter=500,save_init_val=T,save_latent_M=T),
#                       sigma2_control = list(return_sigma2_trace=T))
fit_ebpmf1 = readRDS('/project2/mstephens/dongyue/poisson_mf/sla/sla2000_ebnmf_fit_init1.rds')
```

```{r}
plot(fit_ebpmf1$elbo_trace)
plot(fit_ebpmf1$sigma2_trace[,100])
```

```{r}
p1=structure_plot_general(fit_ebpmf1$fit_flash$L_pm[,-c(1,2)],fit_flash$F_pm,grouping = datax$samples$journal,std_L_method = 'sum_to_1')
p2=structure_plot_general(fit_ebpmf1$fit_flash$L_pm[,-c(1,2)],fit_flash$F_pm,grouping = datax$samples$journal,std_L_method = 'row_max_1')
p3=structure_plot_general(fit_ebpmf1$fit_flash$L_pm[,-c(1,2)],fit_flash$F_pm,grouping = datax$samples$journal,std_L_method = 'col_norm_1')
p4=structure_plot_general(fit_ebpmf1$fit_flash$L_pm[,-c(1,2)],fit_flash$F_pm,grouping = datax$samples$journal,std_L_method = 'col_max_1')
```


### Init 2

```{r}
# fit_ebpmf2 = ebpmf_log(datax$data,
#                       flash_control=list(backfit_extrapolate=T,backfit_warmstart=T,
#                                          ebnm.fn = c(ebnm::ebnm_point_exponential, ebnm::ebnm_point_exponential),
#                                          loadings_sign = 1,factors_sign=1,Kmax=10),
#                       init_control = list(n_cores=5,flash_est_sigma2=T,log_init_for_non0y=F),
#                       general_control = list(maxiter=500,save_init_val=T,save_latent_M=T),
#                       sigma2_control = list(return_sigma2_trace=T))
#saveRDS(fit_ebpmf2,file='/project2/mstephens/dongyue/poisson_mf/sla/sla2000_ebnmf_fit_init2.rds')

fit_ebpmf2 = readRDS('/project2/mstephens/dongyue/poisson_mf/sla/sla2000_ebnmf_fit_init2.rds')
```

```{r}
plot(fit_ebpmf2$elbo_trace)
plot(fit_ebpmf2$sigma2_trace[,100])
```

```{r}
p1=structure_plot_general(fit_ebpmf2$fit_flash$L_pm[,-c(1,2)],fit_flash$F_pm,grouping = datax$samples$journal,std_L_method = 'sum_to_1')
p2=structure_plot_general(fit_ebpmf2$fit_flash$L_pm[,-c(1,2)],fit_flash$F_pm,grouping = datax$samples$journal,std_L_method = 'row_max_1')
p3=structure_plot_general(fit_ebpmf2$fit_flash$L_pm[,-c(1,2)],fit_flash$F_pm,grouping = datax$samples$journal,std_L_method = 'col_norm_1')
p4=structure_plot_general(fit_ebpmf2$fit_flash$L_pm[,-c(1,2)],fit_flash$F_pm,grouping = datax$samples$journal,std_L_method = 'col_max_1')
```

### Init 3


```{r}
# fit_ebpmf3 = ebpmf_log(datax$data,
#                       flash_control=list(backfit_extrapolate=T,backfit_warmstart=T,
#                                          ebnm.fn = c(ebnm::ebnm_point_exponential, ebnm::ebnm_point_exponential),
#                                          loadings_sign = 1,factors_sign=1,Kmax=10),
#                       init_control = list(n_cores=5,flash_est_sigma2=T,log_init_for_non0y=T),
#                       general_control = list(maxiter=500,save_init_val=T,save_latent_M=T),
#                       sigma2_control = list(return_sigma2_trace=T))
# saveRDS(fit_ebpmf3,file='/project2/mstephens/dongyue/poisson_mf/sla/sla2000_ebnmf_fit_init3.rds')

fit_ebpmf3 = readRDS('/project2/mstephens/dongyue/poisson_mf/sla/sla2000_ebnmf_fit_init3.rds')
```

```{r}
plot(fit_ebpmf3$elbo_trace)
plot(fit_ebpmf3$sigma2_trace[,100])
```

```{r}
p1=structure_plot_general(fit_ebpmf3$fit_flash$L_pm[,-c(1,2)],fit_flash$F_pm,grouping = datax$samples$journal,std_L_method = 'sum_to_1')
p2=structure_plot_general(fit_ebpmf3$fit_flash$L_pm[,-c(1,2)],fit_flash$F_pm,grouping = datax$samples$journal,std_L_method = 'row_max_1')
p3=structure_plot_general(fit_ebpmf3$fit_flash$L_pm[,-c(1,2)],fit_flash$F_pm,grouping = datax$samples$journal,std_L_method = 'col_norm_1')
p4=structure_plot_general(fit_ebpmf3$fit_flash$L_pm[,-c(1,2)],fit_flash$F_pm,grouping = datax$samples$journal,std_L_method = 'col_max_1')
```




### Summary


Try to increase the number of words?












