---
title: "hOMEPAGe"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

## Poisson Matrix Factorization


### Analysis

* [Negative Binomial and Poisson log-normal mean-var relationship](NB_PLN_mean_var.html)
* [mean variance relationship in real single cell data](mean_var_relationship_in_real_sc_data.html)
* [attempt to reduce run time](attempt_to_speed_up_add_greedy.html)
* [memory usage analysis](splitting_PMF_memory_issue.html)
* [size of sigma2 on convergence speed](size_of_sigma2_on_convergence.html)
* [fit K=1 on pbmc data](run_splitting_PMF_K1.html)

### Simulation 

* [Splitting method in PMF](PMF_splitting.html)
* [PMF splitting simulation](PMF_splitting_simulation.html)
* [Simulation based on PBMC data, 3 cell types](simulation_based_on_pbmc_3cell.html)
* [Simulation based on PBMC data, 3 cell types, 1 init backfitting](splitting_PMF_1backfitinit.html)

### On pbmc3k

* [run PMF on PBMC data, 3 cell types](run_PMF_on_pbmc_3cells.html)
* [run PMF on PBMC data, 3 cell types, nonnegative loadings](run_PMF_on_pbmc_3cells_nonnegativeL_more_iterations.html)
* [run PMF on PBMC data, 3 cell types, nonnegative loadings and factors](run_PMF_on_pbmc_3cells_nonnegativeLF_more_iterations.html)
* [Compare VGA iterations on PBMC data, 3 cell types](compare_vga_iterations.html)
* [Compare VGA iterations on PBMC data, full dataset](compare_vga_iterations_pbmc_full.html)
* [run PMF on PBMC data](run_PMF_on_pbmc_more_iterations.html)
* [run PMF on PBMC data,nonnegative Loadings](run_PMF_on_pbmc_nonnegativeL_more_iterations.html)
* [run PMF on PBMC data,nonnegative Loadings and factors](run_PMF_on_pbmc_nonnegativeLF_more_iterations.html)
* [library size distribution](library_size_distribution.html)
* [gene specific variance and gene expression](gene_variance_expression.html)
* [Compare latent M from splitting and glmpca](compare_latent_M_splitting_glmpca.html)
* [Run flash on latent M from glmpca](run_flash_on_latent_M_glmpca.html)
* [How do results differ over iterations? When can we stop iterations?](pbmc3k_per_10_iter_plot.html)
* [Use GLMPCA as init](pbmc3k_glmpca_init_for_ebpmf.html)

### On Droplet

* [run PMF on droplet result](run_PMF_on_droplet.Rmd)



## Poisson mean 

* [Poisson log normal](poisson_log_normal.html)
* [NB JJ lower bound](neg_binom_mean_lower_bound.html)
* [NB PG augmentation](neg_binom_mean_polya_gamma.html)
* [NB approxiamation to Poisson](nb_approx_poisson.html)
* [Poisson mean $\log(1+\exp(\cdot))$ link](pois_mean_log1exp.html)
* [VGA objective function v(m) relationship](vga_objective_function.html)

### Penalized

* [Poisson mean penalized form, compound](pois_mean_penalized.html)
* [Poisson mean penalized form, inversion](pois_mean_penalized_inversion.html)

### Benchmarking

* [log link](log_link_benchmark_revised.html)
* [exp prior](exp_prior_benchmark.html)
* [gamma prior](gamma_prior_benchmark.html)
* [t prior](t_prior_benchmark_revise.html)

With Run time Comparison:

* [exp prior with runtime](exp_prior_runtime.html)
* [log prior with runtime](log_prior_runtime.html)

### Overdispersed model

* [generate data from splitting model](overdispersed_splitting.html)
* [generate data from negative binomial model](overdispersed_splitting_nb.html)
* [thoughts on the results](overdispersed_splitting_analysis.html)

## Poisson smoothing 

* [The splitting method smoothing overdispersed count data](poisson_nugget_two_step.html)

### Real data

* [Smooth RNA seq](splitting_smooth_RNAseq.html)

### Bechmarking smoothing methods

I benchmarked methods on the following smooth functions.

* [Angles](smooth_angles_benchmark_new.html)
* [Bursts](smooth_bursts_benchmark_new.html)
* [heavisine](smooth_heavisine_benchmark_new.html)
* [simple blocks](smooth_sblocks_benchmark_new.html)
* [clipped blocks](smooth_cblocks_benchmark_new.html)
* [Spike](smooth_spike_benchmark_new.html)

Below are some old results. Specifically the smooth functions are in the log-space. (So after exp they may look different than their name originally suggest.)

I picked up some methods that are performing better and reduce the plot size for better illustration.

* [Angles](smooth_angles_benchmark_simplified.html)
* [simple blocks](smooth_sblocks_benchmark_simplified.html)
* [spike](smooth_spike_benchmark_simplified.html)

First Run:

* [heavisine](smooth_heavi_benchmark.html)
* [blocks](smooth_blocks_benchmark.html)

Second Run:

* [Angles](smooth_angles_benchmark.html)
* [Bursts](smooth_bursts_benchmark.html)
* [heavisine](smooth_heavisine_benchmark.html)
* [simple blocks](smooth_sblocks_benchmark.html)
* [clipped blocks](smooth_cblocks_benchmark.html)
* [Spike](smooth_spike_benchmark.html)

### Details

* [low count smooth ndwt](splitting_method_low_count_smoothing.html)


## Binomial 

* [Apply Splitting to Binomial Mean problem](binomial_mean_spliiting.html)
* [It does not work for binary data](bernoulli_GG_fail.html)
* [Apply Splitting to Binomial smooth problem](binomial_smooth_splitting.html)

## Normal mean penalty form

* [bound on (log g)''](bound_log_marginal.html)
* [log density of normal mixture](log_gmm_concave.html)
  + [log density of normal mixture, variance ratio](log_gmm_concave_ratio.html)
* [log density of laplace mixture](log_lmm_concave.html)
* [normal mean penalty plots](normal_mean_penalty.html)
* [Solve normal mean problem using optimization - compund penalty](normal_mean_penalized_optimization.html)
* [Solve normal mean problem using optimization - inversion method](normal_mean_penalized_optimization_inversion.html)
* [Solve normal mean problem using optimization - also estimate prior mean](normal_mean_penalized_optimization_prior_mean.html)
* [normal mean penalty plots, when $s^2$ depends on posterior mean](normal_mean_penalty_glm_simplified.html)
* [normal mean penalty plots, when $s^2$ depends on posterior mean, penalty exlcuding $\log(2\pi s^2)/2$ ](remove_log_in_penalty.html)
* [where is the log term from in the penalty](log_term_in_penalty.html)

