---
title: "Negative binomial mean via Jaakkola and Jordan lower bound"
author: "Dongyue Xie"
date: "2022-04-15"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r}
source('code/poisson_mean/neg_binom_mean_lower_bound.R')
```

```{r}
set.seed(12345)
n = 1000 
w = 0.2
mu = c(rep(0.1,n*(1-w)),rep(10,n*w))
x = rnbinom(n, size = 10, mu=mu)
```

# When r is known.

Assume r is given, estimate p.

## point_laplace, mean = estimate

```{r,warning=FALSE}
out = nb_mean_lower_bound(x=x,r=10,
                          maxiter = 2000,
                          tol=1e-8,
                          ebnm_params=list(mode='estimate',prior_family='point_laplace'))
```

```{r}
plot(out$obj,type='l',ylab='ELBO',xlab='iteration')
out$ebnm_res$fitted_g
```

```{r}
plot(x,main='',col='grey80',pch=20)
lines(mu,col='grey50')
lines(out$mean_est,col=4)
legend('topleft',c('data','true mean','estimated mean'),pch=c(20,NA,NA),lty=c(NA,1,1),col=c('grey80','grey50',4))
```

## point_laplace, mean = 0

```{r,warning=FALSE}
out = nb_mean_lower_bound(x=x,r=10,
                          maxiter = 2000,
                          tol=1e-8,
                          ebnm_params=list(mode=0,prior_family='point_laplace'))
```

```{r}
plot(out$obj,type='l',ylab='ELBO',xlab='iteration')
out$ebnm_res$fitted_g
```

```{r}
plot(x,main='',col='grey80',pch=20)
lines(mu,col='grey50')
lines(out$mean_est,col=4)
legend('topleft',c('data','true mean','estimated mean'),pch=c(20,NA,NA),lty=c(NA,1,1),col=c('grey80','grey50',4))
```


## When r is unknown, estimating r is much harder

We start with letting r_init = true r = 10,

```{r}
out = nb_mean_lower_bound(x=x,r=10,est_r=T,update_r_every = 1,
                          maxiter = 1000,
                          tol=1e-8,
                          ebnm_params=list(mode='estimate',prior_family='point_laplace'))

```

```{r}
plot(out$obj,type='l',ylab='ELBO',xlab='iteration')
out$r
out$r_trace
```

```{r}
plot(x,main='',col='grey80',pch=20)
lines(mu,col='grey50')
lines(out$mean_est,col=4)
legend('topleft',c('data','true mean','estimated mean'),pch=c(20,NA,NA),lty=c(NA,1,1),col=c('grey80','grey50',4))
```

The objective dropped. Why?

I checked and it's due to the drop of EBNM log likelihood. I tried different prior families and this problem persists.

```{r}
m = out$m
v = out$v
xi = sqrt(m^2+v)
delta = sum(-xi/2-log(1+exp(-xi))-1/4/xi*tanh(xi/2)*(m^2+v-xi^2)-m/2)
r_vec = 1:50
obj_val = c()
for(r in r_vec){
  obj_val = c(obj_val,Fr_lb(log(r),x,m,v,delta))
}
plot(r_vec,obj_val,type='l')
```



