---
title: "normal mean penalized form optimization"
author: "Dongyue Xie"
date: "2022-05-25"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

\[y\sim N(\mu,s^2),\mu\sim g(\cdot)\]

Optimization: $\theta = E_q\mu$,

\[\min_{\theta,g}h(\theta,g) = \frac{1}{2s^2}(y-\theta)^2+\rho_{g,s}(\theta).\]

Since

\[S_{g,s^2}(z) = z +s^2l'_{NM}(z;g,s^2)\]

Use the compound penalty term $c(z) = \rho(S(z))$, the final problem is

\[\min_{z,g} \tilde h(z,g) = \frac{1}{2s^2}(y-S(z))^2-l_{NM}(z;g,s^2)-(z-S(z))^2/(2s^2)\]

\[\min_{z,g} \tilde h(z,g) = \frac{1}{2s^2}(y-z-s^2l'_{NM}(z;g,s^2))^2-l_{NM}-s^2(l'_{NM})^2/2\]

Then set $\hat\theta = S(z)$. 



```{r}
#'log marginal likelihood of normal mean model
#'@param x scalar 
#'@param g prior, normal mixture
l_nm = function(x,s,w,grid){
  log(sum(w*dnorm(x,0,sqrt(grid^2+s^2))))
}

#'first order derivative of log marginal likelihood of normal mean model
#'@param x scalar 
#'@param g prior, normal mixture
l_nm_d1 = function(x,s,w,grid){
  f = sum(w*dnorm(x,0,sqrt(grid^2+s^2)))
  f_d1 = sum(w*dnorm(x,0,sqrt(grid^2+s^2))*x/(grid^2+s^2))
  f_d1/f
}

softmax = function(a){
  exp(a-max(a))/sum(exp(a-max(a)))
}

#'posterior mean operator
S = function(x,s,w,grid){
  K = length(w)
  g = normalmix(pi=w,mean=rep(0,K),sd=grid)
  fit.ash = ash(x,s,g=g,fixg=T)
  fit.ash$result$PosteriorMean
}

#'objective function
#'@param theta (mu_bar,w)
#'@param grid prior sds
f_obj = function(theta,y,s,grid){
  n = length(y)
  res = 0
  w = softmax(theta[-(1:n)])
  for(i in 1:n){
    res = res + (y[i]-theta[i]-s^2*l_nm_d1(theta[i],s,w,grid))^2/2/s^2 - l_nm(theta[i],s,w,grid) - s^2*(l_nm_d1(theta[i],s,w,grid))^2/2
  }
  res
}

#'objective function with known g
#'@param theta (mu_bar)
#'@param grid prior sds
f_obj_known_g = function(theta,y,s,w,grid){
  n = length(y)
  res = 0
  #w = softmax(theta[-(1:n)])
  for(i in 1:n){
    res = res + (y[i]-theta[i]-s^2*l_nm_d1(theta[i],s,w,grid))^2/2/s^2 - l_nm(theta[i],s,w,grid) - s^2*(l_nm_d1(theta[i],s,w,grid))^2/2
  }
  res
}
```

## ash fit

```{r,warning=FALSE}
set.seed(12345)
n = 200
w0 = 0.9
lambda = c(rep(0,round(n*w0)),rep(10,n-round(n*w0)))
w_true = c(w0,1-w0)
grid_true = c(0.01,7)
s = 1
y = rnorm(n,lambda,s)
library(ashr)
fit.ash = ashr::ash(y,s,mixcompdist = 'normal')
#grid = exp(seq(log(s/100),log(sqrt(max(abs(y^2-s^2)))),by=log(sqrt(2))))
#fit.ash = S(y,s,w_true,grid_true)
#plot(fit.ash$fitted_g$sd,fit.ash$fitted_g$pi)
grid = fit.ash$fitted_g$sd
grid = grid[-1]
K = length(grid)

plot(y,main='ash fit',col='grey80')
lines(lambda,col='grey60')
lines(fit.ash$result$PosteriorMean)
legend('topleft',c('data','true mean','ash posteriorMean'),pch=c(1,NA,NA),lty=c(NA,1,1),col=c('grey80','grey60',1))
```

## Known prior

### Init $z$ at data $y$.

```{r}
fit = optim(c(y),f_obj_known_g,method='BFGS',y=y,grid=grid_true,s=s,w=w_true)
fit$value
```

```{r}
plot(y,main='known prior',col='grey80')
lines(lambda,col='grey60')
lines(fit$par,type='p',pch=20,col='grey80')
lines(S(fit$par,s,c(w0,1-w0),c(0.01,7)))
legend('topleft',c('data','true mean','z','estimated mean'),pch=c(1,20,NA,NA),lty=c(NA,NA,1,1),col=c('grey80','grey80','grey60',1))
```


### Init $z$ at 0.

```{r}
fit = optim(rep(0,n),f_obj_known_g,method='BFGS',y=y,grid=grid_true,s=s,w=w_true)
fit$value
```

```{r}
plot(y,main='known prior',col='grey80')
lines(lambda,col='grey60')
lines(fit$par,type='p',pch=20,col='grey80')
lines(S(fit$par,s,c(w0,1-w0),c(0.01,7)))
legend('topleft',c('data','true mean','z','estimated mean'),pch=c(1,20,NA,NA),lty=c(NA,NA,1,1),col=c('grey80','grey80','grey60',1))
```

## Estimate prior

## init at y

```{r}
mu_init = y
w_init = rep(1/K,K)
fit = optim(c(mu_init,w_init),f_obj,method='BFGS',y=y,grid=grid,s=s)
fit$value
round(softmax(fit$par[-(1:n)]),2)
plot(grid,round(softmax(fit$par[-(1:n)]),2),ylab='w hat')
```


```{r}
plot(y,main='estimated prior',col='grey80')
lines(lambda,col='grey60')
lines(fit$par[1:n],type='p',pch=20,col='grey80')
lines(S(fit$par[1:n],s,softmax(fit$par[-(1:n)]),grid))
legend('topleft',c('data','true mean','z','estimated mean'),pch=c(1,20,NA,NA),lty=c(NA,NA,1,1),col=c('grey80','grey80','grey60',1))
```

## init at 0

```{r}
mu_init = rep(0,n)
w_init = rep(1/K,K)
fit = optim(c(mu_init,w_init),f_obj,method='BFGS',y=y,grid=grid,s=s)
fit$value
round(softmax(fit$par[-(1:n)]),2)
plot(grid,round(softmax(fit$par[-(1:n)]),2),ylab='w hat')
```


```{r}
plot(y,main='estimated prior',col='grey80')
lines(lambda,col='grey60')
lines(fit$par[1:n],type='p',pch=20,col='grey80')
lines(S(fit$par[1:n],s,softmax(fit$par[-(1:n)]),grid))
legend('topleft',c('data','true mean','z','estimated mean'),pch=c(1,20,NA,NA),lty=c(NA,NA,1,1),col=c('grey80','grey80','grey60',1))
```







