---
title: "normal mean penalty when variance depends on posterior mean"
author: "Dongyue Xie"
date: "2022-10-03"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

\begin{equation}
\begin{split}
        \rho(\theta;g)= \min_{q:\E_q=\theta} &\frac{1}{s^2(\theta)}\Var(q) + D(q||g) + \frac{1}{2}\log2\pi s^2(\theta).
\end{split}
\end{equation}

The inversion $S^{-1}_{g,s^2(\theta)}(\theta)$ finds the $z$ such that $S_{g,s^2(\theta)}(z) = \theta$. Then the penalty can be evaluated as 
\begin{equation}
    \rho(\theta;g) = \rho_{g,s^2(\theta)}(S_{g,s^2(\theta)}(z)).
\end{equation}

I use `pracma::grad` for calculating the gradient.

```{r}
source('code/normal_mean_model_utils.R')
pois_penalty = function(theta,w,grid){
  s = sqrt(exp(-theta))
  return(nm_penalty(theta,s,w,grid))
}
pois_penalty_grad = function(theta,w,grid){
  n = length(theta)
  out = c()
  for(i in 1:n){
    out[i] = pracma::grad(pois_penalty,theta[i],heps=0.1,w=w,grid=grid)
  }
  return(out)
}
pois_penalty_hess = function(theta,w,grid){
  n = length(theta)
  out = c()
  for(i in 1:n){
    out[i] = pracma::grad(pois_penalty_grad,theta[i],heps=0.1,w=w,grid=grid)
  }
  return(out)
}
```

```{r}
theta = seq(-5,5,length.out = 501)
w = c(0.9,0.1)
grid = c(0.01,2)
par(mfrow=c(1,2))
plot(theta,pois_penalty(theta,w,grid),type='l',ylab='penalty')
plot(theta,pois_penalty_grad(theta,w,grid),type='l',ylab='penalty gradient')
#plot(theta,pois_penalty_hess(theta,w,grid),type='l',ylab='penalty hessian')
```

```{r}
theta = seq(-5,5,length.out = 501)
w = c(0.9,0.1)
grid = c(0.01,3)
par(mfrow=c(1,2))
plot(theta,pois_penalty(theta,w,grid),type='l',ylab='penalty')
plot(theta,pois_penalty_grad(theta,w,grid),type='l',ylab='penalty gradient')
#plot(theta,pois_penalty_hess(theta,w,grid),type='l',ylab='penalty hessian')
```


```{r}
theta = seq(-5,5,length.out = 501)
w = c(0.9,0.1)
grid = c(0.01,4)
par(mfrow=c(1,2))
plot(theta,pois_penalty(theta,w,grid),type='l',ylab='penalty')
plot(theta,pois_penalty_grad(theta,w,grid),type='l',ylab='penalty gradient')
#plot(theta,pois_penalty_hess(theta,w,grid),type='l',ylab='penalty hessian')
```

```{r}
theta = seq(-5,5,length.out = 501)
w = c(0.9,0.1)
grid = c(0.01,5)
par(mfrow=c(1,2))
plot(theta,pois_penalty(theta,w,grid),type='l',ylab='penalty')
plot(theta,pois_penalty_grad(theta,w,grid),type='l',ylab='penalty gradient')
#plot(theta,pois_penalty_hess(theta,w,grid),type='l',ylab='penalty hessian')
```
