---
title: "Normal Mean problem Penalty"
author: "Dongyue Xie"
date: "2022-05-28"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

The normal mean penalty term evaluated at $S(\cdot)$, the posterior mean operator, is 

\[c(\theta) = \rho(S(\theta)) = -l_{NM}(\theta;g,s^2)-\frac{(\theta-S_{g,s}(\theta))^2}{2s^2}\]

To evaluate $\rho(\theta)$, we find $z$ such that $S(z) = \theta$ then $\rho(\theta) = \rho(S(z))$.

```{r}
#'density of log g(x)
#'x is a scalar
lg = function(x,w,s2){
  return(log(sum(w*dnorm(x,0,sd=sqrt(s2)))))
}

#'density of log g(x)
#'x is a vector
lg_vec = function(x,w,s2){
  n = length(x)
  out = rep(0,n)
  for(i in 1:n){
    out[i] = lg(x[i],w,s2)
  }
  return(out)
}
```

```{r}
library(ashr)
library(ebnm)
#g = normalmix(pi = c(0,w),mean=rep(0,K+1),sd = c(0,sqrt(s2)))


nm = function(z,g,s){
  fit = ash(z,s,g = g,fixg = T)
  return(list(l_nm = fit$loglik, pm=fit$result$PosteriorMean))
}

penalty = function(theta,g,s){
  temp = nm(theta,g,s)
  return(-temp$l_nm - (theta-temp$pm)^2/2/s^2)
}

penalty_vec = function(x,g,s){
  n = length(x)
  out = rep(0,n)
  for(i in 1:n){
    out[i] = penalty(x[i],g,s)
  }
  return(out)
}




#'posterior mean operator
S = function(z,g,s){
  pw = log(g$pi)+dnorm(z,mean=0,sd=sqrt(s^2+g$sd^2),log=TRUE)
  pw = pw - max(pw)
  pw = exp(pw)/sum(exp(pw))
  pm = z/(1+s^2/g$sd^2)
  return(sum(pw*pm))
}

#'Solve S(z) = theta for a given theta
#'@param theta 
#'@param g a normalmix object with weights pi and sd
#'@param s known standard error
inv_S = function(theta,g,s=1){
  eqn = function(z,theta,g,s){
    S(z,g,s) - theta
  }
  if(theta==0){
    sol = 0
  }else if(theta>0){
    sol = uniroot(eqn,interval=c(0,theta/min(1/(1+s^2/g$sd^2))),theta=theta,g=g,s=s)$root
  }else{
    sol = uniroot(eqn,interval=c(theta/min(1/(1+s^2/g$sd^2)),0),theta=theta,g=g,s=s)$root
  }
  return(sol)
}

inv_S_vec = function(x,g,s=1){
  n = length(x)
  out = c()
  for(i in 1:n){
    out[i] = inv_S(x[i],g,s)
  }
  out
}


plot_penalty = function(x,g,s=1){
  
  
  # plot compound penalty
  compound_penalty = penalty_vec(x,g,s)
  z = inv_S_vec(x,g,s)
  original_penalty = penalty_vec(z,g,s)
  
  plot(x,compound_penalty,type='l',xlab='theta',ylab='penalty',ylim=range(c(compound_penalty,original_penalty)),
       main=paste('w=(',paste(g$pi,collapse = ", "),'); sd=(',paste(g$sd,collapse = ", "),')',sep=''))
  lines(x,original_penalty,col='blue',lty=2)
  legend('bottomright',c(expression(rho(S(theta))),expression(rho(theta))),lty=c(1,2),col=c(1,'blue'))
}

```

```{r}
x = seq(-10,10,length.out = 101)
g = normalmix(pi = c(0.9,0.1),mean=rep(0,2),sd = c(0.1,2))
plot_penalty(x,g)
```

```{r}
x = seq(-10,10,length.out = 101)
g = normalmix(pi = c(0.5,0.5),mean=rep(0,2),sd = c(0.1,2))
plot_penalty(x,g)
```

```{r}
x = seq(-30,30,length.out = 101)
g = normalmix(pi = c(0.1,0.9),mean=rep(0,2),sd = c(0.1,2))
plot_penalty(x,g)
```

```{r}
x = seq(-10,10,length.out = 101)
g = normalmix(pi = c(0.9,0.1),mean=rep(0,2),sd = c(1,2))
plot_penalty(x,g)
```

```{r}
x = seq(-20,20,length.out = 101)
g = normalmix(pi = c(0.1,0.9),mean=rep(0,2),sd = c(1,2))
plot_penalty(x,g)
```

```{r,eval=FALSE}
x = seq(-5,5,length.out = 101)
g = normalmix(pi = c(0.9,0.1),mean=rep(0,2),sd = c(0.1,0.2))
plot_penalty(x,g)
```

Scale mixture of 19 normal distributions.

```{r}
#'softmax
softmax = function(a){
  exp(a-max(a))/sum(exp(a-max(a)))
}
s2 = exp(seq(-8,5,by=log(2)))
w = softmax(log(1/s2))
round(w,2)
round(s2,2)
K = length(w)
g = normalmix(pi = w,mean=rep(0,K),sd = sqrt(s2))
x = seq(-10,10,length.out = 101)
plot_penalty(x,g)
```

