---
title: "Overdispersed splitting method"
author: "DongyueXie"
date: "2022-11-19"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Generate data from Splitting model

We simulate data from the following model,

$$y_i\sim Poisson(\exp(\mu_i)),\mu_i|b_i\sim N(b_i,\sigma^2), b_i\sim \pi_0\delta_0 + \pi_1\ N(0,2).$$
And Run splitting method with fixed and known $\sigma^2$.

```{r}
library(vebpm)
library(ashr)
```

```{r}
simu_func = function(n_simu=10,n,sigma2,prior_mean=0,w=0.8,prior_var = 2,seed = 12345,n_plot = 3){
  set.seed(seed)
  mse_b = c()
  mse_exp_b = c()
  for(i in 1:n_simu){
    b = c(rep(prior_mean,round(n*w)) , rnorm(round(n*(1-w)),prior_mean,sqrt(prior_var)))
    mu = rnorm(n,b,sigma2)
    y = rpois(n,exp(mu))
    fit_ash = ash_pois(y)
    fit_split_ash_init = pois_mean_split(y,sigma2=sigma2,est_sigma2 = FALSE,mu_pm_init = fit_ash$result$PosteriorMean)
    fit_split_logx = pois_mean_split(y,sigma2=sigma2,est_sigma2 = FALSE,mu_pm_init = NULL)
    mse_b = rbind(mse_b,c(mse(log(fit_ash$result$PosteriorMean),(b)),
                          mse(fit_split_ash_init$posterior$mean_b,b),
                          mse(fit_split_logx$posterior$mean_b,b)))
    mse_exp_b = rbind(mse_exp_b,c(mse(fit_ash$result$PosteriorMean,exp(b)),
                                  mse(fit_split_ash_init$posterior$mean_exp_b,exp(b)),
                                  mse(fit_split_logx$posterior$mean_exp_b,exp(b))))
    
    colnames(mse_b) = c('ash','split ash init','split logx init')
    colnames(mse_exp_b) = c('ash','split ash init','split logx init')
    if(i<=n_plot){
      par(mfrow=c(3,1))
      plot(b,col='grey80',ylab='b',main='ash')
      lines(log(fit_ash$result$PosteriorMean))
      plot(b,col='grey80',ylab='b',main='splitting ash init')
      lines(fit_split_ash_init$posterior$mean_b)
      plot(b,col='grey80',ylab='b',main='splitting logx init')
      lines(fit_split_logx$posterior$mean_b)
    }
    
  }
  return(list(mse_b = mse_b,mse_exp_b = mse_exp_b))
  
}
```

# prior mean = 0

## $\sigma^2 = 0.5$

```{r,warning=F,fig.width=4,fig.height=6}
res1 = simu_func(n_simu = 10,n=1000,sigma2=0.5,n_plot = 10)
colMeans(res1$mse_exp_b)
colMeans(res1$mse_b)
```

## $\sigma^2 = 1$

```{r,warning=F,fig.width=4,fig.height=6}
res1 = simu_func(n_simu = 10,n=1000,sigma2=1,n_plot = 10)
colMeans(res1$mse_exp_b)
colMeans(res1$mse_b)
```

## $\sigma^2 = 0.1$

```{r,warning=F,fig.width=4,fig.height=6}
res1 = simu_func(n_simu = 10,n=1000,sigma2=0.1,n_plot = 10)
colMeans(res1$mse_exp_b)
colMeans(res1$mse_b)
```

# prior mean = 5

## $\sigma^2 = 0.5$

```{r,warning=F,fig.width=4,fig.height=6}
res1 = simu_func(n_simu = 10,n=1000,sigma2=0.5,n_plot = 10,prior_mean = 5)
colMeans(res1$mse_exp_b)
colMeans(res1$mse_b)
```

## $\sigma^2 = 1$

```{r,warning=F,fig.width=4,fig.height=6}
res1 = simu_func(n_simu = 10,n=1000,sigma2=1,n_plot = 10,prior_mean = 5)
colMeans(res1$mse_exp_b)
colMeans(res1$mse_b)
```

## $\sigma^2 = 0.1$

```{r,warning=F,fig.width=4,fig.height=6}
res1 = simu_func(n_simu = 10,n=1000,sigma2=0.1,n_plot = 10,prior_mean = 5)
colMeans(res1$mse_exp_b)
colMeans(res1$mse_b)
```
