---
title: "flash, glmpca, and topic model fit on pbmc data in fasttopics package"
author: "DongyueXie"
date: "2023-02-23"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

I take the pbmc dataset from fasttopics package, and fit flash, glmpca, as well as topic model on the dataset.

```{r}
library(fastTopics)
library(flashier)
library(glmpca)
library(Matrix)
data("pbmc_facs")
counts = pbmc_facs$counts
counts = counts[,colSums(counts!=0)>10]
```

```{r}
source("~/Rpackages/gsmash/code/poisson_STM/structure_plot.R")
source("~/Rpackages/gsmash/code/poisson_STM/plot_factors_general.R")
```



## GLMPCA Poisson

I set K = 10

```{r}
glmpca_fit_poi = readRDS('/project2/mstephens/dongyue/poisson_mf/pbmc_fasttopics/othermethods/glmpca_poi.rds')
```

```{r}
plot.factors.general(glmpca_fit_poi$factors,cell.types = pbmc_facs$samples$subpop,title = 'glmpca poisson')
plot.factors.general(glmpca_fit_poi$factors,cell.types = pbmc_facs$samples$celltype,title = 'glmpca poisson')
```

## GLMPCA NB

I set K = 10

```{r}
glmpca_fit_poi = readRDS('/project2/mstephens/dongyue/poisson_mf/pbmc_fasttopics/othermethods/glmpca_nb.rds')
```

```{r}
plot.factors.general(glmpca_fit_poi$factors,cell.types = pbmc_facs$samples$subpop,title = 'glmpca NB')
plot.factors.general(glmpca_fit_poi$factors,cell.types = pbmc_facs$samples$celltype,title = 'glmpca NB')
```

## flash sparse


```{r}
flash_sparse = readRDS('/project2/mstephens/dongyue/poisson_mf/pbmc_fasttopics/othermethods/flash_sparse.rds')
```


```{r}
K_plot = 10
kset = order(flash_sparse$pve,decreasing = T)[1:K_plot]
plot.factors.general(flash_sparse$L.pm[,kset],cell.types = pbmc_facs$samples$subpop,title = 'flash sparse')
plot.factors.general(flash_sparse$L.pm[,kset],cell.types = pbmc_facs$samples$celltype,title = 'flash sparse')
```


## flash nonneg Loadings


```{r}
flash_nonnegL = readRDS('/project2/mstephens/dongyue/poisson_mf/pbmc_fasttopics/othermethods/flash_nonnegL.rds')
```


```{r}
plot.factors.general(flash_nonnegL$L.pm,cell.types = pbmc_facs$samples$subpop,title = 'flash nonnegL',nonnegative = T)
plot.factors.general(flash_nonnegL$L.pm,cell.types = pbmc_facs$samples$celltype,title = 'flash nonnegL',nonnegative = T)
```


```{r}
library(randomcoloR)
n <- 20
set.seed(12345)
palette <- distinctColorPalette(n)
#kset = order(flash_nonnegL$pve,decreasing = T)[1:K_plot]
structure_plot_general(flash_nonnegL$L.pm,
                       flash_nonnegL$F.pm,
                       grouping = pbmc_facs$samples$subpop, 
                       title='flash nonnegL',
                       colors = palette,
                       remove_l0f0 = FALSE,
                       print_plot = F,
                       LD=T)
# structure_plot_general(flash_nonnegL$L.pm,flash_nonnegL$F.pm,grouping = pbmc_facs$samples$celltype,
#                        title='flash nonnegL',remove_l0f0 = FALSE,LD=T)
```

```{r}
kset = order(flash_nonnegL$pve,decreasing = T)[1:20]
structure_plot_general(flash_nonnegL$L.pm[,kset[-c(1,2)]],
                       flash_nonnegL$F.pm[,kset[-c(1,2)]],
                       grouping = pbmc_facs$samples$subpop,
                       title='flash nonnegL',
                       colors = palette,
                       remove_l0f0 = FALSE,
                       print_plot = F,
                       LD=T)
```

```{r}
structure_plot_general(flash_nonnegL$L.pm[,kset[-c(1,2,3)]],
                       flash_nonnegL$F.pm[,kset[-c(1,2,3)]],
                       grouping = pbmc_facs$samples$subpop,
                       title='flash nonnegL',
                       colors = palette,
                       remove_l0f0 = FALSE,
                       LD=T,print_plot = F
                      )
```


## flash nonneg Loadings and factors


```{r}
flash_nonnegLF = readRDS('/project2/mstephens/dongyue/poisson_mf/pbmc_fasttopics/othermethods/flash_nonnegLF.rds')
```


```{r}
plot.factors.general(flash_nonnegLF$L.pm,cell.types = pbmc_facs$samples$subpop,title = 'flash nonnegLF',nonnegative = T)
plot.factors.general(flash_nonnegLF$L.pm,cell.types = pbmc_facs$samples$celltype,title = 'flash nonnegLF',nonnegative = T)
```


```{r}
structure_plot_general(flash_nonnegLF$L.pm,
                       flash_nonnegLF$F.pm,
                       grouping = pbmc_facs$samples$subpop,
                       title='flash nonnegLF',
                       colors = palette,
                       print_plot = F,
                       remove_l0f0 = FALSE,LD=T)
kset = order(flash_nonnegLF$pve,decreasing = T)[1:20]
structure_plot_general(flash_nonnegLF$L.pm[,kset[-1]],
                       flash_nonnegLF$F.pm[,kset[-1]],
                       grouping = pbmc_facs$samples$subpop,
                       title='flash nonnegLF',
                       colors = palette,
                       print_plot = F,
                       remove_l0f0 = FALSE,LD=T)

structure_plot_general(flash_nonnegLF$L.pm[,kset[-1]],
                       flash_nonnegLF$F.pm[,kset[-1]],
                       grouping = pbmc_facs$samples$celltype,
                       title='flash nonnegLF',
                       remove_l0f0 = FALSE,
                       print_plot = F,
                       colors = palette,
                       LD=T)
```

## Topic model

```{r}
tm = readRDS('/project2/mstephens/dongyue/poisson_mf/pbmc_fasttopics/othermethods/fasttopics_fit.rds')
```


```{r}
tm = poisson2multinom(tm)
plot.factors.general(tm$L,cell.types = pbmc_facs$samples$subpop,title = 'topic model',nonnegative = T)
plot.factors.general(tm$L,cell.types = pbmc_facs$samples$celltype,title = 'topic model',nonnegative = T)
```

```{r}
structure_plot_general(tm$L,tm$F,grouping = pbmc_facs$samples$subpop,
                       title='topic model',remove_l0f0 = FALSE,LD=F,topic_model = T)
structure_plot_general(tm$L,tm$F,grouping = pbmc_facs$samples$celltype,
                       title='topic model',remove_l0f0 = FALSE,LD=F,topic_model = T)
```





