---
title: "Poisson smoothing benchmark"
author: "DongyueXie"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Introduction

In this analysis we look at the results from generating data as 

$$y_i\sim Poisson(\exp(b_i+\epsilon_i)),\epsilon_i\sim N(0,\sigma^2).$$

The signal $\exp(b)$ is smooth.

We set $n=1024$, repeat 30 times, and $=max(\exp(b))\in \{5,10,100\}$, and $snr = var(b)/\sigma^2\in \{1,3\}$.

```{r}
library(tidyverse)
source('code/poisson_smooth/simulation_summary_smooth.R')
```

## save plots, run time vs mse

```{r}
snr_list = c(1,3)
count_size_list = c(5,10,100)
smooth_func_list = c('sblocks','cblocks','heavi','angles','bursts','spike')


for(snr in snr_list){
  for (count_size in count_size_list) {
    pch = 1:11
    col = 1:11
    if(count_size==100){
      rm_method = 'smash'
    }else{
      rm_method = NULL
    }
    pdf(file = paste("/home/dyxie/Rpackages/gsmash/output/plots/smooth_n_1024_snr_",snr,"_count_size_",count_size,".pdf",sep=''),   # The directory you want to save the file in
    width = 9.1, # The width of the plot in inches
    height = 11.43) # The height of the plot in inches

    par(mfrow=c(3,2))
    for(smooth_func in smooth_func_list){
      file_path = paste("/project2/mstephens/dongyue/poisson_smooth/simu_2023/results/",smooth_func,"30_n_1024_snr_",snr,"_count_size_",count_size,".rds",sep='')
      out = readRDS(file_path)
      if(smooth_func=='sblocks'){
        function_name = 'simple blocks'
      }else if(smooth_func=='cblocks'){
        function_name = 'clipped blocks'
      }else{
        function_name = smooth_func
      }
      
      res = c()
      for(i in 1:length(out$output)){
        res = rbind(res,out$output[[i]]$mse_smooth)
      }
      res = sqrt(res)
    
      res_time = c()
      for(i in 1:length(out$output)){
        res_time = rbind(res_time,out$output[[i]]$run_times)
      }
    
      methods = colnames(res)
      if(!is.null(rm_method)){
        idx = match(rm_method,methods)
        res = res[,-idx]
        res_time = res_time[,-idx]
        methods = methods[-idx]
        pch = pch[-idx]
        col=col[-idx]
      }
      n_methods = length(methods)
    
      res_mean = colMeans(res,na.rm=T)
      res_time_mean = colMeans(res_time,na.rm=T)
      
      methods[methods=='smash_two_step'] = 'two_step'
      methods[methods=='smash_two_step_hetero'] = 'two_step_hetero'
    
      plot(log2(res_time_mean),res_mean,xlab='run time(log2, seconds)',ylab='RMSE',pch = 1:n_methods,col=1:n_methods, main=function_name)
      if(smooth_func=='sblocks'){
        legend('topright',methods,pch=pch,col=col)
      }
      
    }
    dev.off()
  }
}

```




## save plots, fitted curve

```{r}
plot_all_curves = function(out,method,method_name_for_plot=NULL,add_legend = TRUE){
  #x_median = apply(out$sim_data$X,2,median)
  #plot(x_median,col='grey80',xlab='',ylab='x(median of all runs)',main=method,ylim=range(out$sim_data$X))

  if(is.null(method_name_for_plot)){
    method_name_for_plot = method
  }
  
  ylim_upper = max(exp(out$sim_data$b))
  for(i in 1:length(out$output)){
  if(class(out$output[[i]]$fitted_model[[method]])!='try-error'){
    ylim_upper = max(ylim_upper,max(out$output[[i]]$fitted_model[[method]]$posterior$mean_smooth))
  }
    }

  
  plot(exp(out$sim_data$b),xlab='',ylab='',main=method_name_for_plot,ylim = c(0,ylim_upper),type='l')
  for(i in 1:length(out$output)){
    if(class(out$output[[i]]$fitted_model[[method]])!='try-error'){
      lines(out$output[[i]]$fitted_model[[method]]$posterior$mean_smooth,col='grey80')
    }
  }
  lines(exp(out$sim_data$b))


  res = c()
  for(i in 1:length(out$output)){
    res = rbind(res,out$output[[i]]$mse_smooth)
  }
  methods = colnames(res)
  res0 = res[,match(method,methods)]
  lines(out$output[[which.min(res0)]]$fitted_model[[method]]$posterior$mean_smooth,col=2,lwd=1.5)
  lines(out$output[[which.max(res0)]]$fitted_model[[method]]$posterior$mean_smooth,col=4,lwd=1.5)
  if(add_legend){
    legend('topright',c('True mean','best fit','worst fit','all others'),lty=c(1,1,1,1),col=c(1,2,4,'grey80'))
  }
  

}
```

```{r}

snr = 1
count_size = 5
methods = c('vst_hetero','lik_exp','split_vga_ndwt','smash_two_step_hetero')
method_names = list(vst_hetero = 'VST(hetero)',lik_exp='likelihood expansion',split_vga_ndwt='splitting(VGA, NDWT)',smash_two_step_hetero = 'two step(hetero)')
for(smooth_func in smooth_func_list){
  
  pdf(file = paste("/home/dyxie/Rpackages/gsmash/output/plots/smooth_",smooth_func,"_n_1024_snr_",snr,"_count_size_",count_size,".pdf",sep=''),  
    width = 11.7, # The width of the plot in inches
    height = 8.3) # The height of the plot in inches
  par(mfrow=c(2,2))
  file_path = paste("/project2/mstephens/dongyue/poisson_smooth/simu_2023/results/",smooth_func,"30_n_1024_snr_",snr,"_count_size_",count_size,".rds",sep='')
  out = readRDS(file_path)
  for(i in 1:length(methods)){
    method = methods[i]
    if(i>1){
      plot_all_curves(out,method=method,method_name_for_plot = method_names[[method]],add_legend = F)
    }else{
      plot_all_curves(out,method=method,method_name_for_plot = method_names[[method]],add_legend = ifelse(smooth_func=='cblocks',F,T))
    }
    
  }
  dev.off()
}


```


```{r}
snr = 1
count_size = 100
methods = c('vst_hetero','lik_exp_top','split_vga_ndwt','smash_two_step_hetero')
method_names = list(vst_hetero = 'VST(hetero)',lik_exp_top='likelihood expansion(large counts for nugget)',split_vga_ndwt='splitting(VGA, NDWT)',smash_two_step_hetero = 'two step(hetero)')
for(smooth_func in smooth_func_list){
  
  pdf(file = paste("/home/dyxie/Rpackages/gsmash/output/plots/smooth_",smooth_func,"_n_1024_snr_",snr,"_count_size_",count_size,".pdf",sep=''),  
    width = 11.7, # The width of the plot in inches
    height = 8.3) # The height of the plot in inches
  par(mfrow=c(2,2))
  file_path = paste("/project2/mstephens/dongyue/poisson_smooth/simu_2023/results/",smooth_func,"30_n_1024_snr_",snr,"_count_size_",count_size,".rds",sep='')
  out = readRDS(file_path)
  for(i in 1:length(methods)){
    method = methods[i]
    if(i>1){
      plot_all_curves(out,method=method,method_name_for_plot = method_names[[method]],add_legend = F)
    }else{
      plot_all_curves(out,method=method,method_name_for_plot = method_names[[method]],add_legend = ifelse(smooth_func=='cblocks',F,T))
    }
    
  }
  dev.off()
}

```


## real data 

RNA-seq

```{r}
library(smashrgen)
files = list.files('/project2/mstephens/dongyue/gtex/Yang/CoverageCounts')
idx = 4

for(f in files[2:4]){
  datax = read.table(paste('/project2/mstephens/dongyue/gtex/Yang/CoverageCounts/',f,sep=''),
                   header = TRUE)
  fs = strsplit(f,split='_')
  gene_name = fs[[1]][1]
  fs = strsplit(fs[[1]][2],split = ':')
  chr = fs[[1]][1]

  y = (datax[,idx])
  indi_name = colnames(datax)[idx]
  
  fit_vst = smash_gen_pois(y,transformation='vst',smoother='smash',
                                          filter.number = 1,family = 'DaubExPhase',
                                          est_nugget = FALSE,
                                          homoskedastic = T)
  fit_split = ebps(y, init_control = list(m_init_method='vga'),
                                            smooth_control = list(wave_trans='ndwt',
                                                                  ndwt_method = 'smash'),
                                            general_control = list(maxiter=30))
  fit_lik_exp = smash_gen_pois(y,transformation='lik_expan',smoother='smash',
                                                est_nugget_maxiter=2,lik_expan_at = 'logx',est_nugget = TRUE,
                                                ash_pm_init_for0 = TRUE,
                                                nug.est.limit = 0.3)
  fit_two_step = smash_two_step(y,homoskedastic=FALSE)
  
  pdf(file = paste("/home/dyxie/Rpackages/gsmash/output/plots/smooth_",gene_name,"_",indi_name,"_vst.pdf",sep=''),  
    width = 11,
    height = 5) 
  plot(y,col='grey80',type='p',pch=20,cex=1,ylab='counts',xlab=paste('Chr',chr),xaxt = "n",main=gene_name)
  xlab.idx = round(seq(1,nrow(datax),length.out = 5))
  axis(1, at = xlab.idx,labels = datax[xlab.idx,2])
  lines(fit_vst$posterior$mean_smooth,col=2,lwd=2)
  dev.off()
  
    pdf(file = paste("/home/dyxie/Rpackages/gsmash/output/plots/smooth_",gene_name,"_",indi_name,"_split.pdf",sep=''),  
    width = 11,
    height = 5) 
  plot(y,col='grey80',type='p',pch=20,cex=1,ylab='counts',xlab=paste('Chr',chr),xaxt = "n",main=gene_name)
  xlab.idx = round(seq(1,nrow(datax),length.out = 5))
  axis(1, at = xlab.idx,labels = datax[xlab.idx,2])
  lines(fit_split$posterior$mean_smooth,col=2,lwd=2)
  dev.off()
  
    pdf(file = paste("/home/dyxie/Rpackages/gsmash/output/plots/smooth_",gene_name,"_",indi_name,"_lik_exp.pdf",sep=''),  
    width = 11,
    height = 5) 
  plot(y,col='grey80',type='p',pch=20,cex=1,ylab='counts',xlab=paste('Chr',chr),xaxt = "n",main=gene_name)
  xlab.idx = round(seq(1,nrow(datax),length.out = 5))
  axis(1, at = xlab.idx,labels = datax[xlab.idx,2])
  lines(fit_lik_exp$posterior$mean_smooth,col=2,lwd=2)
  dev.off()
  
    pdf(file = paste("/home/dyxie/Rpackages/gsmash/output/plots/smooth_",gene_name,"_",indi_name,"_two_step.pdf",sep=''),  
    width = 11,
    height = 5) 
  plot(y,col='grey80',type='p',pch=20,cex=1,ylab='counts',xlab=paste('Chr',chr),xaxt = "n",main=gene_name)
  xlab.idx = round(seq(1,nrow(datax),length.out = 5))
  axis(1, at = xlab.idx,labels = datax[xlab.idx,2])
  lines(fit_two_step$posterior$mean_smooth,col=2,lwd=2)
  dev.off()
}



```



Chip seq:

```{r}
extract_counts_CTCF <- function(filename){
  bed_counts <- read.table(filename, header = F, stringsAsFactors = F)
  colnames(bed_counts) <- c("chr", "start", "end", "name", "width", "counts")

  counts <- strsplit(bed_counts$counts, split = ",")[[1]]
  counts[counts == "NA"] <- 0
  counts <- as.numeric(counts)

  return(counts.l = list(chr = bed_counts$chr, start = bed_counts$start, end = bed_counts$end, counts = counts))
}
```

```{r}
files = list.files('/home/dyxie/Rpackages/smash-gen/data/chipexo_examples')
file.name = paste("/home/dyxie/Rpackages/smash-gen/data/chipexo_examples/",files[1],sep='')
chipexo1 = extract_counts_CTCF(file.name)
y = chipexo1$counts




fit_vst = smash_gen_pois(y,transformation='vst',smoother='smash',
                                          filter.number = 1,family = 'DaubExPhase',
                                          est_nugget = FALSE,
                                          homoskedastic = T)
fit_split = ebps(y, init_control = list(m_init_method='vga'),
                                          smooth_control = list(wave_trans='ndwt',
                                                                ndwt_method = 'smash'),
                                          general_control = list(maxiter=30))
fit_lik_exp = smash_gen_pois(y,transformation='lik_expan',smoother='smash',
                                              est_nugget_maxiter=2,lik_expan_at = 'logx',est_nugget = TRUE,
                                              ash_pm_init_for0 = TRUE,
                                              nug.est.limit = 1)
fit_two_step = smash_two_step(y,homoskedastic=FALSE)

plot(y, col = "gray80", type = "p", pch=20,ylab = "counts", xlab = 'Chr 1',xaxt='n', main = 'Rep 1, Forward')
xlab.idx = round(seq(1,length(chipexo1$counts),length.out = 5))
axis(1, at = xlab.idx,labels = round(seq(chipexo1$start,chipexo1$end,length.out = 5)))

lines(smash.poiss(y), col = "grey70", lwd = 1)
lines(fit_vst$posterior$mean_smooth,col=3,lwd=1)
lines(fit_lik_exp$posterior$mean_smooth,col='black',lwd=1)
lines(fit_split$posterior$mean_smooth,col=2,lwd=2)
lines(fit_two_step$posterior$mean_smooth,lwd=1,col=4)

legend("topright", # places a legend at the appropriate place
       c("data","smash",'VST','lik exp','two step','splitting'), # puts text in the legend
       lty=c(NA,1,1,1,1,1), # gives the legend appropriate symbols (lines)
       pch=c(20,NA,NA,NA,NA,NA),
       lwd=c(1,1,1,1,1,2),
       cex = 0.7,
       col=c("gray80","gray70", 3,1,4,2))
```


```{r}
file.name = paste("/home/dyxie/Rpackages/smash-gen/data/chipexo_examples/",files[2],sep='')
chipexo1 = extract_counts_CTCF(file.name)
y = chipexo1$counts

fit_vst = smash_gen_pois(y,transformation='vst',smoother='smash',
                                          filter.number = 1,family = 'DaubExPhase',
                                          est_nugget = FALSE,
                                          homoskedastic = T)
fit_split = ebps(y, init_control = list(m_init_method='vga'),
                                          smooth_control = list(wave_trans='ndwt',
                                                                ndwt_method = 'smash'),
                                          general_control = list(maxiter=30))
fit_lik_exp = smash_gen_pois(y,transformation='lik_expan',smoother='smash',
                                              est_nugget_maxiter=2,lik_expan_at = 'logx',est_nugget = TRUE,
                                              ash_pm_init_for0 = TRUE,
                                              nug.est.limit = 1)
fit_two_step = smash_two_step(y,homoskedastic=FALSE)

plot(y, col = "gray80", type = "p", pch=20,ylab = "counts", xlab = 'Chr 1',xaxt='n', main = 'Rep 1, Reverse')
xlab.idx = round(seq(1,length(chipexo1$counts),length.out = 5))
axis(1, at = xlab.idx,labels = round(seq(chipexo1$start,chipexo1$end,length.out = 5)))

lines(smash.poiss(y), col = "grey70", lwd = 1)
lines(fit_vst$posterior$mean_smooth,col=3,lwd=1)
lines(fit_lik_exp$posterior$mean_smooth,col='black',lwd=1)
lines(fit_split$posterior$mean_smooth,col=2,lwd=2)
lines(fit_two_step$posterior$mean_smooth,lwd=1,col=4)

legend("topleft", # places a legend at the appropriate place
       c("data","smash",'VST','lik exp','two step','splitting'), # puts text in the legend
       lty=c(NA,1,1,1,1,1), # gives the legend appropriate symbols (lines)
       pch=c(20,NA,NA,NA,NA,NA),
       lwd=c(1,1,1,1,1,2),
       cex = 0.7,
       col=c("gray80","gray70", 3,1,4,2))
```




```{r}
file.name = paste("/home/dyxie/Rpackages/smash-gen/data/chipexo_examples/",files[3],sep='')
chipexo1 = extract_counts_CTCF(file.name)
y = chipexo1$counts

fit_vst = smash_gen_pois(y,transformation='vst',smoother='smash',
                                          filter.number = 1,family = 'DaubExPhase',
                                          est_nugget = FALSE,
                                          homoskedastic = T)
fit_split = ebps(y, init_control = list(m_init_method='vga'),
                                          smooth_control = list(wave_trans='ndwt',
                                                                ndwt_method = 'smash'),
                                          general_control = list(maxiter=30))
fit_lik_exp = smash_gen_pois(y,transformation='lik_expan',smoother='smash',
                                              est_nugget_maxiter=2,lik_expan_at = 'logx',est_nugget = TRUE,
                                              ash_pm_init_for0 = TRUE,
                                              nug.est.limit = 1)
fit_two_step = smash_two_step(y,homoskedastic=FALSE)

plot(y, col = "gray80", type = "p", pch=20,ylab = "counts", xlab = 'Chr 1',xaxt='n', main = 'Rep 2, Forward')
xlab.idx = round(seq(1,length(chipexo1$counts),length.out = 5))
axis(1, at = xlab.idx,labels = round(seq(chipexo1$start,chipexo1$end,length.out = 5)))

lines(smash.poiss(y), col = "grey70", lwd = 1)
lines(fit_vst$posterior$mean_smooth,col=3,lwd=1)
lines(fit_lik_exp$posterior$mean_smooth,col='black',lwd=1)
lines(fit_split$posterior$mean_smooth,col=2,lwd=2)
lines(fit_two_step$posterior$mean_smooth,lwd=1,col=4)

legend("topright", # places a legend at the appropriate place
       c("data","smash",'VST','lik exp','two step','splitting'), # puts text in the legend
       lty=c(NA,1,1,1,1,1), # gives the legend appropriate symbols (lines)
       pch=c(20,NA,NA,NA,NA,NA),
       lwd=c(1,1,1,1,1,2),
       cex = 0.7,
       col=c("gray80","gray70", 3,1,4,2))
```


```{r}
file.name = paste("/home/dyxie/Rpackages/smash-gen/data/chipexo_examples/",files[4],sep='')
chipexo1 = extract_counts_CTCF(file.name)
y = chipexo1$counts

fit_vst = smash_gen_pois(y,transformation='vst',smoother='smash',
                                          filter.number = 1,family = 'DaubExPhase',
                                          est_nugget = FALSE,
                                          homoskedastic = T)
fit_split = ebps(y, init_control = list(m_init_method='vga'),
                                          smooth_control = list(wave_trans='ndwt',
                                                                ndwt_method = 'smash'),
                                          general_control = list(maxiter=30))
fit_lik_exp = smash_gen_pois(y,transformation='lik_expan',smoother='smash',
                                              est_nugget_maxiter=2,lik_expan_at = 'logx',est_nugget = TRUE,
                                              ash_pm_init_for0 = TRUE,
                                              nug.est.limit = 1)
fit_two_step = smash_two_step(y,homoskedastic=FALSE)

plot(y, col = "gray80", type = "p", pch=20,ylab = "counts", xlab = 'Chr 1',xaxt='n', main = 'Rep 2, Reverse')
xlab.idx = round(seq(1,length(chipexo1$counts),length.out = 5))
axis(1, at = xlab.idx,labels = round(seq(chipexo1$start,chipexo1$end,length.out = 5)))

lines(smash.poiss(y), col = "grey70", lwd = 1)
lines(fit_vst$posterior$mean_smooth,col=3,lwd=1)
lines(fit_lik_exp$posterior$mean_smooth,col='black',lwd=1)
lines(fit_split$posterior$mean_smooth,col=2,lwd=2)
lines(fit_two_step$posterior$mean_smooth,lwd=1,col=4)

legend("topleft", # places a legend at the appropriate place
       c("data","smash",'VST','lik exp','two step','splitting'), # puts text in the legend
       lty=c(NA,1,1,1,1,1), # gives the legend appropriate symbols (lines)
       pch=c(20,NA,NA,NA,NA,NA),
       lwd=c(1,1,1,1,1,2),
       cex = 0.7,
       col=c("gray80","gray70", 3,1,4,2))
```




Chip exo:

```{r}
extract_counts_CTCF <- function(filename){
  bed_counts <- read.table(filename, header = F, stringsAsFactors = F)
  colnames(bed_counts) <- c("chr", "start", "end", "name", "width", "counts")

  counts <- strsplit(bed_counts$counts, split = ",")[[1]]
  counts[counts == "NA"] <- 0
  counts <- as.numeric(counts)

  return(counts.l = list(chr = bed_counts$chr, start = bed_counts$start, end = bed_counts$end, counts = counts))
}
```

```{r}
files = list.files('/home/dyxie/Rpackages/smash-gen/data/chipseq_examples')
file.name = paste("/home/dyxie/Rpackages/smash-gen/data/chipseq_examples/",files[3],sep='')
chipexo1 = extract_counts_CTCF(file.name)
y = chipexo1$counts




fit_vst = smash_gen_pois(y,transformation='vst',smoother='smash',
                                          filter.number = 1,family = 'DaubExPhase',
                                          est_nugget = FALSE,
                                          homoskedastic = T)
fit_split = ebps(y, init_control = list(m_init_method='smash_poi'),
                                          smooth_control = list(wave_trans='ndwt',
                                                                ndwt_method = 'smash'),
                                          general_control = list(maxiter=30))
fit_lik_exp = smash_gen_pois(y,transformation='lik_expan',smoother='smash',
                                              est_nugget_maxiter=2,lik_expan_at = 'logx',est_nugget = TRUE,
                                              ash_pm_init_for0 = TRUE,
                                              nug.est.limit = 1)
fit_two_step = smash_two_step(y,homoskedastic=FALSE)

plot(y, col = "gray80", type = "p", pch=20,ylab = "counts", xlab = 'Chr 1',xaxt='n', main = 'Rep 1, Forward')
xlab.idx = round(seq(1,length(chipexo1$counts),length.out = 5))
axis(1, at = xlab.idx,labels = round(seq(chipexo1$start,chipexo1$end,length.out = 5)))

lines(smash.poiss(y), col = "grey70", lwd = 1)
lines(fit_vst$posterior$mean_smooth,col=3,lwd=1)
lines(fit_lik_exp$posterior$mean_smooth,col='black',lwd=1)
lines(fit_split$posterior$mean_smooth,col=2,lwd=2)
lines(fit_two_step$posterior$mean_smooth,lwd=1,col=4)

legend("topright", # places a legend at the appropriate place
       c("data","smash",'VST','lik exp','two step','splitting'), # puts text in the legend
       lty=c(NA,1,1,1,1,1), # gives the legend appropriate symbols (lines)
       pch=c(20,NA,NA,NA,NA,NA),
       lwd=c(1,1,1,1,1,2),
       cex = 0.7,
       col=c("gray80","gray70", 3,1,4,2))
```

```{r}
file.name = paste("/home/dyxie/Rpackages/smash-gen/data/chipseq_examples/",files[5],sep='')
chipexo1 = extract_counts_CTCF(file.name)
y = chipexo1$counts




fit_vst = smash_gen_pois(y,transformation='vst',smoother='smash',
                                          filter.number = 1,family = 'DaubExPhase',
                                          est_nugget = FALSE,
                                          homoskedastic = T)
fit_split = ebps(y, init_control = list(m_init_method='smash_poi'),
                                          smooth_control = list(wave_trans='ndwt',
                                                                ndwt_method = 'smash'),
                                          general_control = list(maxiter=30))
fit_lik_exp = smash_gen_pois(y,transformation='lik_expan',smoother='smash',
                                              est_nugget_maxiter=2,lik_expan_at = 'logx',est_nugget = TRUE,
                                              ash_pm_init_for0 = TRUE,
                                              nug.est.limit = 1)
fit_two_step = smash_two_step(y,homoskedastic=FALSE)

plot(y, col = "gray80", type = "p", pch=20,ylab = "counts", xlab = 'Chr 1',xaxt='n', main = 'Rep 2, Forward')
xlab.idx = round(seq(1,length(chipexo1$counts),length.out = 5))
axis(1, at = xlab.idx,labels = round(seq(chipexo1$start,chipexo1$end,length.out = 5)))

lines(smash.poiss(y), col = "grey70", lwd = 1)
lines(fit_vst$posterior$mean_smooth,col=3,lwd=1)
lines(fit_lik_exp$posterior$mean_smooth,col='black',lwd=1)
lines(fit_split$posterior$mean_smooth,col=2,lwd=2)
lines(fit_two_step$posterior$mean_smooth,lwd=1,col=4)

legend("topright", # places a legend at the appropriate place
       c("data","smash",'VST','lik exp','two step','splitting'), # puts text in the legend
       lty=c(NA,1,1,1,1,1), # gives the legend appropriate symbols (lines)
       pch=c(20,NA,NA,NA,NA,NA),
       lwd=c(1,1,1,1,1,2),
       cex = 0.7,
       col=c("gray80","gray70", 3,1,4,2))
```


```{r}
file.name = paste("/home/dyxie/Rpackages/smash-gen/data/chipseq_examples/",files[4],sep='')
chipexo1 = extract_counts_CTCF(file.name)
y = chipexo1$counts
sum(y==0)/length(y)



fit_vst = smash_gen_pois(y,transformation='vst',smoother='smash',
                                          filter.number = 1,family = 'DaubExPhase',
                                          est_nugget = FALSE,
                                          homoskedastic = T)
fit_split = ebps(y, init_control = list(m_init_method='smash_poi'),
                                          smooth_control = list(wave_trans='ndwt',
                                                                ndwt_method = 'smash'),
                                          general_control = list(maxiter=30))
fit_lik_exp = smash_gen_pois(y,transformation='lik_expan',smoother='smash',
                                              est_nugget_maxiter=2,lik_expan_at = 'logx',est_nugget = TRUE,
                                              ash_pm_init_for0 = TRUE,
                                              nug.est.limit = 1)
fit_two_step = smash_two_step(y,homoskedastic=FALSE)

plot(y, col = "gray80", type = "p", pch=20,ylab = "counts", xlab = 'Chr 1',xaxt='n', main = 'Rep 1, Reverse')
xlab.idx = round(seq(1,length(chipexo1$counts),length.out = 5))
axis(1, at = xlab.idx,labels = round(seq(chipexo1$start,chipexo1$end,length.out = 5)))

lines(smash.poiss(y), col = "grey70", lwd = 1)
lines(fit_vst$posterior$mean_smooth,col=3,lwd=1)
lines(fit_lik_exp$posterior$mean_smooth,col='black',lwd=1)
lines(fit_split$posterior$mean_smooth,col=2,lwd=2)
lines(fit_two_step$posterior$mean_smooth,lwd=1,col=4)

legend("topright", # places a legend at the appropriate place
       c("data","smash",'VST','lik exp','two step','splitting'), # puts text in the legend
       lty=c(NA,1,1,1,1,1), # gives the legend appropriate symbols (lines)
       pch=c(20,NA,NA,NA,NA,NA),
       lwd=c(1,1,1,1,1,2),
       cex = 0.7,
       col=c("gray80","gray70", 3,1,4,2))
```


```{r}
file.name = paste("/home/dyxie/Rpackages/smash-gen/data/chipseq_examples/",files[6],sep='')
chipexo1 = extract_counts_CTCF(file.name)
y = chipexo1$counts
sum(y==0)/length(y)



fit_vst = smash_gen_pois(y,transformation='vst',smoother='smash',
                                          filter.number = 1,family = 'DaubExPhase',
                                          est_nugget = FALSE,
                                          homoskedastic = T)
fit_split = ebps(y, init_control = list(m_init_method='smash_poi'),
                                          smooth_control = list(wave_trans='ndwt',
                                                                ndwt_method = 'smash'),
                                          general_control = list(maxiter=30))
fit_lik_exp = smash_gen_pois(y,transformation='lik_expan',smoother='smash',
                                              est_nugget_maxiter=2,lik_expan_at = 'logx',est_nugget = TRUE,
                                              ash_pm_init_for0 = TRUE,
                                              nug.est.limit = 1)
fit_two_step = smash_two_step(y,homoskedastic=FALSE)

plot(y, col = "gray80", type = "p", pch=20,ylab = "counts", xlab = 'Chr 1',xaxt='n', main = 'Rep 2, Reverse')
xlab.idx = round(seq(1,length(chipexo1$counts),length.out = 5))
axis(1, at = xlab.idx,labels = round(seq(chipexo1$start,chipexo1$end,length.out = 5)))

lines(smash.poiss(y), col = "grey70", lwd = 1)
lines(fit_vst$posterior$mean_smooth,col=3,lwd=1)
lines(fit_lik_exp$posterior$mean_smooth,col='black',lwd=1)
lines(fit_split$posterior$mean_smooth,col=2,lwd=2)
lines(fit_two_step$posterior$mean_smooth,lwd=1,col=4)

legend("topright", # places a legend at the appropriate place
       c("data","smash",'VST','lik exp','two step','splitting'), # puts text in the legend
       lty=c(NA,1,1,1,1,1), # gives the legend appropriate symbols (lines)
       pch=c(20,NA,NA,NA,NA,NA),
       lwd=c(1,1,1,1,1,2),
       cex = 0.7,
       col=c("gray80","gray70", 3,1,4,2))
```

