---
title: "run PMF on droplet dataset"
author: "DongyueXie"
date: "2022-12-07"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r}
fit = readRDS('/project2/mstephens/dongyue/poisson_mf/droplet/ebpmf_droplet_vga3.rds')
load('/project2/mstephens/pcarbo/git/single-cell-topics/data/droplet.RData')
source('code/poisson_STM/plot_factors.R')
source('code/poisson_STM/plot_factors_general.R')

```

```{r}
dim(counts)
table(samples$tissue)
```

```{r}
fit$run_time
plot(fit$elbo_trace,type='l')
plot(fit$K_trace,type='l')
plot(fit$fit_flash$pve)
plot(fit$sigma2_trace[,which.max(fit$sigma2)],type='l',ylab='',main='convergence of largest sigma2')
round(unlist(lapply(fit$run_time_break_down,median)),3)
```

```{r}
plot.factors(fit$fit_flash,samples$tissue,title='splitting PMF')
```

```{r}
glmpca_nb = readRDS('/project2/mstephens/dongyue/poisson_mf/droplet/glmpca_droplet_nb.rds')
glmpca_poi = readRDS('/project2/mstephens/dongyue/poisson_mf/droplet/glmpca_droplet_poi.rds')
flash_fit = readRDS('/project2/mstephens/dongyue/poisson_mf/droplet/flash_droplet.rds')
```

```{r}
plot.factors(flash_fit,samples$tissue,title='flash')
```

```{r}
plot.factors.general(glmpca_poi$loadings,samples$tissue,title='glmpca pois')
plot.factors.general(glmpca_nb$loadings,samples$tissue,title='glmpca nb')
```




