---
title: "sla data, ebmf fit with known intercept"
author: "DongyueXie"
date: "2023-07-22"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction


We fit EBNMF model on SLA data, but fix the intercept (of factors) as:

colMeans(data_matrix)

```{r}
library(Matrix)
datax = readRDS('data/sla_2000.rds')
dim(datax$data)
sum(datax$data==0)/prod(dim(datax$data))
datax$data = Matrix(datax$data,sparse = TRUE)
```

Recall that the transformation for EBNMF for count data is 

\[\log ( 1+ \frac{median(s_i)}{0.5}\frac{y_{ij}}{s_i}).\]

```{r}
library(ebpmf)
Y_tilde = log_for_ebmf(datax$data)
f0 = colMeans(Y_tilde)
plot(f0)
```

Then we subtract $1f_0^T$ to remove this intercept.

```{r}
Y = Y_tilde - rep(1,nrow(Y_tilde))%*%t(f0)
```

Then we fit EBNMF

```{r}
library(flashier)
fit = flash(Y,ebnm=ebnm::ebnm_point_exponential,greedy.Kmax = 6,var.type = 2,backfit = T)
```


```{r}
colnames(datax$data)[order(fit$F.pm[,1],decreasing = T)[1:10]]
colnames(datax$data)[order(fit$F.pm[,2],decreasing = T)[1:10]]
colnames(datax$data)[order(fit$F.pm[,3],decreasing = T)[1:10]]
colnames(datax$data)[order(fit$F.pm[,4],decreasing = T)[1:10]]
colnames(datax$data)[order(fit$F.pm[,5],decreasing = T)[1:10]]
colnames(datax$data)[order(fit$F.pm[,6],decreasing = T)[1:10]]
```










