source("code/poisson_mean/pois_mean_GG.R")
source("code/poisson_mean/pois_mean_GMG.R")
source("code/poisson_mean/pois_mean_GMGM.R")
source("code/poisson_mean/neg_binom_mean_lower_bound.R")
source("code/poisson_mean/neg_binom_mean_polya_gamma.R")
source("code/poisson_mean/pois_mean_log1exp.R")
source("code/poisson_mean/pois_mean_spliting.R")
source("code/poisson_mean/pois_mean_spliting_mixture.R")
source("code/poisson_mean/pois_mean_penalized_compound.R")
source("code/poisson_mean/pois_mean_penalized_inversion.R")
source("code/poisson_mean/simulation_study.R")

datax = gen_data_identity(n=1000,n_simu=30,prior='gamma')
res = simu_study_poisson_mean(datax,n_cores = 10)
saveRDS(res,file='output/poisson_mean_simulation/gamma_prior.rds')
